b_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
]

blogs/urls.py
"""Defines URL patterns for blogs."""

from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page to view all blogs
    path('blogs/', views.blogs, name='blogs'),
    # Page for viewing individual blog
    path('blogs/<int:blog_id>/', views.blog, name='blog'),
    # Page for creating new blog
    path('new_blog/', views.new_blog, name='new_blog'),
    # Page for creating blog post
    path('new_post/<int:blog_id>/', views.new_post, name='new_post'),
    # Page for editing a post
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
]

blogs/models.py
from django.db import models

class Blog(models.Model):
    """A user's blog."""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name
    
class Post(models.Model):
    """Individual post in blog."""
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return sring representation of the post."""
        if len(self.title) > 50:
            return f"{self.title[:50]}..."
        else:
            return self.title
    

blogs/forms.py
from django import forms

from .models import Blog, Post

class BlogForm(forms.ModelForm):
    """Form for creating new blog."""
    class Meta:
        model = Blog
        fields = ['name']
        labels = {'name': ''}

class PostForm(forms.ModelForm):
    """Form for creating post for a blog."""
    class Meta:
        model = Post
        fields = ['title', 'body']
        widgets = {'body': forms.Textarea(attrs={'cols': 80})}

blogs/views.py
from django.shortcuts import render, redirect

from .models import Blog, Post
from .forms import BlogForm, PostForm

def index(request):
    """The home page for the Blog."""
    return render(request, 'blogs/index.html')

def blogs(request):
    """Page to view all blogs."""
    blogs = Blog.objects.all()
    context = {'blogs': blogs}
    return render(request, 'blogs/blogs.html', context)

def blog(request, blog_id):
    """Page to view selected blog and its posts."""
    blog = Blog.objects.get(id=blog_id)
    posts = blog.post_set.order_by('-date_added')
    context = {'blog': blog, 'posts': posts}
    return render(request, 'blogs/blog.html', context)

def new_blog(request):
    """Add a new blog."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = BlogForm()
    else:
        # POST data submitted; process data.
        form = BlogForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blogs')
        
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)

def new_post(request, blog_id):
    """Add a new post for a blog."""
    blog = Blog.objects.get(id=blog_id)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = PostForm()
    else:
        # POST data submitted; process data.
        form = PostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.blog = blog
            new_post.save()
            return redirect('blogs:blog', blog_id=blog_id)
        
    # Display a blank or invalid form.
    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/new_post.html', context)

def edit_post(request, post_id):
    """Edit existing post."""
    post = Post.objects.get(id=post_id)
    blog = post.blog

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = PostForm(instance=post)
    else:
        # POST data submitted; process data.
        form = PostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blog', blog_id=blog.id)
        
    context = {'post': post, 'blog': blog, 'form': form}
    return render(request, 'blogs/edit_post.html', context)

blogs/templates/blogs/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog</title>

    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

  </head>
  <body>
    
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blogs:index' %}">Blog</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blogs:blogs' %}">Blogs</a>
            </li>
          </ul><!-- End of links on left side of navbar -->
        </div> <!-- Closes collasible parts of navbar -->
      </div> <!-- Closes navbar's container -->
    </nav> <!-- End of navbar -->

    <main class="container">
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
      </div>
    </main>
  
  {% block content %}{% endblock content %}

</body>
</html>

blogs/templates/blogs/blog.html
{% extends 'blogs/base.html' %}

{% block content %}

  <p>Blog: {{ blog.name }}</p>

  <p>Posts:</p>
  <p>
    <a href="{% url 'blogs:new_post' blog.id %}">Add a new post</a>
  </p>
  <ul>
    {% for post in posts %}
      <li>
        <p>{{ post.date_added|date:'M d, Y H:i' }}</p>
        <p>{{ post.title }}</p>
        <p>{{ post.body|linebreaks }}</p>
        <p>
          <a href="{% url 'blogs:edit_post' post.id %}">
            Edit post</a></p>
      </li>
    {% empty %}
      <li>There are no posts associated with this blog.</li>
    {% endfor %}
  </ul>

{% endblock content %}

blogs/templates/blogs/blogs.html
{% extends 'blogs/base.html' %}

{% block page_header %}
  <h1>Blogs</h1>
{% endblock page_header %}

{% block content %}

    <ul class="list-group border-bottom pb-2 mb-4">
      {% for blog in blogs %}
        <li class="list-group-item border-0">
          <a href="{% url 'blogs:blog' blog.id %}">
            {{ blog.name }}</a>
        </li>
      {% empty %}
        <li class="list-group-item border-0">No blogs currently created.</li>
      {% endfor %}
    </ul>

    <a href="{% url 'blogs:new_blog' %}">Add a new blog</a>

{% endblock content %}

blogs/templates/blogs/edit_post.html
{% extends 'blogs/base.html' %}

{% block content %}

  <p><a href="{% url 'blogs:blog' blog.id %}">{{ blog }}</a></p>

  <p>Edit post:</p>

  <form action="{% url 'blogs:edit_post' post.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_div }}
    <button name="submit">Save changes</button>
  </form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}

{% block page_header %}
  <div class="p-3 mb-4 bg-light border rounded-3">
    <div class="container-fluid py-4">
      <h1 class="display-3">Create a blog.</h1>

      <p class="lead">Create your own blog and update it with as many posts as you'd like to share.</p>

      <a class="btn btn-primary btn-lg mt-1" href="{% url 'blogs:new_blog' %}">Create a Blog</a>
    </div>
  </div>
{% endblock page_header %}


{% block content %}

{% endblock content %}

blogs/templates/blogs/new_blog.html
{% extends 'blogs/base.html' %}

{% block content %}
  <p>Add a new blog:</p>

  <form action="{% url 'blogs:new_blog' %}" method='post'>
    {% csrf_token %}
    {{ form.as_div }}
    <button name="submit">Add blog</button>
  </form>

{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends 'blogs/base.html' %}

{% block content %}

  <p><a href="{% url 'blogs:blog' blog.id %}">{{ blog }}</a></p>

  <p>Add a new post:</p>
  <form action="{% url 'blogs:new_post' blog.id %}" method='post'>

    {% csrf_token %}
    {{ form.as_div }}
    <button name='submit'>Add post</button>
  </form>

{% endblock content %}